version: "3"

networks:
 app_network:
  external: true

services:
 emailserver:
  image: jacknam/emailserver:1.0
  container_name: emailserver
  restart: ${RESTART_MODE}
  domainname: ${MAILSERVER_DOMAIN} # Mail server A/MX/FQDN & reverse PTR = mail.domain.tld.
  hostname: ${MAILSERVER_HOSTNAME}
  extra_hosts:
  # integrated local db - 127.0.0.1, local db - ${MAILSERVER_GATEWAY}, external db - ip address, docker db - skip this config
   - "mariadb:127.0.0.1"
   - "redis:127.0.0.1"
  ports:
   - "25:25" # SMTP - Required
  # - "110:110" # POP3 - Optional
   - "143:143" # IMAP - Optional
  # - "465:465" # SMTPS - Optional
   - "587:587" # Submission - Optional
   - "993:993" # IMAPS - Optional
  # - "995:995" # POP3S - Optional
   - "4190:4190" # SIEVE - Optional
   - "4191:3306" # MARIADB - Optional
   - "8081:8081" # RAINLOOP - Optional
   - "8082:11334" # RSPAMD WEB - Optional
   - "8083:8083" # POSTFIXADMIN - Optional
   - "8084:8084" # PHPMYADMIN - Optional
  environment:
   - DBPASS=${DATABASE_USER_PASSWORD} # MariaDB database password (required)
   - RSPAMD_PASSWORD=${RSPAMD_PASSWORD} # Rspamd WebUI password (required)
   - ADMINIP=${MAILSERVER_ADMIN_IP}
  # - GATEWAY_IP=${MAILSERVER_GATEWAY}
  # - DISABLE_RAINLOOP=true # Disable local rainloop
  # - DISABLE_POSTFIXADMIN=true # Disable local postfixadmin
  # - DISABLE_PHPMYADMIN=true # Disable local phpmyadmin
  # - ADD_DOMAINS=aa.tld, www.bb.tld... # Add additional domains separated by commas (needed for dkim keys etc.)
  # - DEBUG_MODE=true # Enable Postfix, Dovecot, Rspamd and Unbound verbose logging
  # - ENABLE_POP3=true # Enable POP3 protocol
  # - ENABLE_FETCHMAIL=true # Enable fetchmail forwarding
  # - DISABLE_RATELIMITING=false # Enable ratelimiting policy
  # - DISABLE_CLAMAV=true # Disable virus scanning
  # - DISABLE_SIGNING=true # Disable DKIM/ARC signing
  # - DISABLE_GREYLISTING=true # Disable greylisting policy
  volumes:
   - ${VOLUMES_ROOT_PATH}/mail:/var/mail
   - ${VOLUMES_ROOT_PATH}/ssl:/etc/letsencrypt
  networks:
   - app_network
