#!/bin/bash

# Launch all services in order
# -----------------------------------------------------------
# 1. rsyslogd      (logger)
# 2. unbound       (dns resolver)
# 3. redis         (redis-serever)
# 4. mariadb       (mysql server)
# 5. postfix       (smtp server)
# 6. dovecot       (imap/pop server)
# 7. rspamd        (anti-spam)
# 8. cron          (job scheduler)
# 9. freshclam     (clamav database updater)
# 10. clamd        (antivirus, is launched after database update)
# 11. watcher      (watches for cert file changes)
# 12. postfixadmin (postfix admin php web)
# 13. phpmyadmin   (mysql admin php web)
# 14. rainloop     (webmail php web)

s6-svc -u /services/rsyslogd && s6-svwait -u /services/rsyslogd
s6-svc -u /services/unbound  && [ "$DISABLE_DNS_RESOLVER" = true ] || s6-svwait -u /services/unbound
s6-svc -u /services/redis && s6-svwait -u /services/redis
s6-svc -u /services/mariadb && s6-svwait -u /services/mariadb
s6-svc -u /services/postfix  && s6-svwait -u /services/postfix
s6-svc -u /services/dovecot
s6-svc -u /services/rspamd
s6-svc -u /services/cron

if [ "$DISABLE_CLAMAV" = false ]; then
 s6-svc -u /services/freshclam
 if [ -f "/var/mail/clamav-unofficial-sigs/user.conf" ]; then
  logger -p mail.info "s6-supervise : clamav unofficial signature update running"
  clamav-unofficial-sigs.sh &>/dev/null
  logger -p mail.info "s6-supervise : clamav unofficial signature update done"
 fi
 s6-svwait -u /services/clamd
fi

s6-svc -u /services/cert_watcher
s6-svc -u /services/postfixadmin
s6-svc -u /services/phpmyadmin
s6-svc -u /services/rainloop

sleep 2
logger -p mail.info "s6-supervise : (_parent) all my wonderful children have started, i can die in peace :)"
exit 0
