#!/bin/bash

# if not using local redis-server, then exit
cat /etc/hosts | grep redis | grep -q 127.0.0.1 || exit 0

if ! redis_entrypoint.sh; then
 logger -p mail.info "s6-supervise : failed to initialize redis process"
 exit 0
fi

logger -p mail.info "s6-supervise : spawning redis process"
echo $$ > /var/run/redis/redis-server.pid
redis-server /etc/redis/redis.conf
sleep infinity
