#!/bin/bash

# if not using local mariadb-server, then exit
cat /etc/hosts | grep mariadb | grep -q 127.0.0.1 || exit 0

if ! mariadb_entrypoint.sh; then
 logger -p mail.info "s6-supervise : failed to initialize mariadb process"
 exit 0
fi

logger -p mail.info "s6-supervise : spawning mariadb process"
exec mysqld
